use_frameworks!

platform :ios, '11.0'

target 'JPSuspensionEntrance_Example' do
  pod 'JPSuspensionEntrance', :path => '../'
  pod 'JPBasic/JPConst'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
  
end
